# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca127fc705855496a8f57374b1443980a4f0140b6ba30f04ff2cfd7af36bba0d9384d1088bffe786b38bcf305bd12817b0a0d65c0d2d5a9b4576427be83813f9

test:
  secret_key_base: 1a07ff7502314b696ace017895ad0b799cfbdb5e68e832f7ad360ac192bb32dc825023078584bf9628048c85700f81f0211d14d6cded634ca1116cd926620408

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
